### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LittleLuni** [FelixReuthlinger/AutoMapPins#3] opened 2023-08-26 03:52 UTC
When starting Valheim with this mod installed, this error is throw in Console upon reaching the main menu, It also prevents the ingame console from opening at all during at point of play.

[Error  : Unity Log] MissingMethodException: void Terminal/ConsoleCommand..ctor(string,string,Terminal/ConsoleEvent,bool,bool,bool,bool,bool,Terminal/ConsoleOptionsFetcher)
Stack trace:
(wrapper dynamic-method) Console.DMD<Console::Awake>(Console)
UnityEngine.Object:Instantiate(GameObject)
FejdStartup:DMD<FejdStartup::Awake>(FejdStartup)

**Comment by sfjuocekr** [comment] 2023-08-28 00:01
+1

Just realized this plugin was preventing the console from working!

**Comment by FelixReuthlinger** [comment] 2023-08-28 17:14
The exception shown in the issue could be created by any mod and I do not get any if I just run the updated version of Valheim with the mod in the latest version. Game loads normal, console opens regularly.

But I have seen this issue when using mods like "Server_devcommands by JereKuusela", not sure if he updated it, yet. I had this mod installed before, but removing the "Server_devcommands by JereKuusela" did also resolve the issue.

Complete game log:
```
[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (5/17/2023 11:05:58 AM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2105 from Thunderstore
[Info   :   BepInEx] Running under Unity v2020.3.45.6687953
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 18.0]
[Info   :   BepInEx] Loading [Jotunn 2.12.5]
[Info   :    Jotunn] Initializing LocalizationManager
[Info   :    Jotunn] Initializing CommandManager
[Info   :    Jotunn] Initializing InputManager
[Info   :    Jotunn] Initializing SkillManager
[Info   :    Jotunn] Initializing PrefabManager
[Info   :    Jotunn] Initializing ItemManager
[Info   :    Jotunn] Initializing PieceManager
[Info   :    Jotunn] Initializing CreatureManager
[Info   :    Jotunn] Initializing ZoneManager
[Info   :    Jotunn] Initializing MockManager
[Info   :    Jotunn] Initializing KitbashManager
[Info   :    Jotunn] Initializing GUIManager
[Info   :    Jotunn] Initializing KeyHintManager
[Info   :    Jotunn] Initializing NetworkManager
[Info   :    Jotunn] Initializing SynchronizationManager
[Info   :    Jotunn] Initializing RenderManager
[Info   :    Jotunn] Initializing MinimapManager
[Info   :    Jotunn] Initializing UndoManager
[Info   :    Jotunn] Jötunn v2.12.5 loaded successfully
[Info   :   BepInEx] Loading [AutoMapPins 1.1.5]
[Info   :FixItFelix.AutoMapPins] found category and pin config file 'C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\config\FixItFelix.AutoMapPins.categories.vanilla.yaml'
[Info   :FixItFelix.AutoMapPins] loaded 16 categories and a total of 188 pins across all categories from configuration
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 08/28/2023 19:10:41: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 08/28/2023 19:10:41: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Info   : Unity Log] 08/28/2023 19:10:41: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 08/28/2023 19:10:49: Using steam_appid.txt

[Info   : Unity Log] 08/28/2023 19:10:49: Using steam APPID:892970

[Info   : Unity Log] 08/28/2023 19:10:49: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 08/28/2023 19:10:49: Steam initialized, persona:Flux

[Info   : Unity Log] 08/28/2023 19:10:49: PlayFab custom ID set to "Steam_76561198005900763"

[Info   : Unity Log] 08/28/2023 19:10:49: Using default prefs

[Info   : Unity Log] 08/28/2023 19:10:49: Valheim version: 0.217.14 (network version 12)

[Info   : Unity Log] 08/28/2023 19:10:49: Worldgenerator version setup:2

[Info   :Jotunn.Managers.CommandManager] Adding 1 commands to the Console
[Info   : Unity Log] 08/28/2023 19:10:49: Render threading mode:MultiThreaded

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 08/28/2023 19:10:49: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Warning: Unity Log] 08/28/2023 19:10:49: Missing audio clip in music respawn

[Info   : Unity Log] 08/28/2023 19:10:49: Checking for installed DLCs

[Info   : Unity Log] 08/28/2023 19:10:49: DLC:beta installed:False

[Info   : Unity Log] 08/28/2023 19:10:50: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 08/28/2023 19:10:50: Session auth respons callback

[Info   : Unity Log] 08/28/2023 19:10:50: Starting music menu

[Info   : Unity Log] 08/28/2023 19:10:51: PlayFab logged in as "Steam_76561198005900763"

[Info   : Unity Log] 08/28/2023 19:10:51: PlayFab local entity ID is 42ED38254CE4EA1A

[Info   : Unity Log] 08/28/2023 19:10:54: show character selection

[Info   : Unity Log] 08/28/2023 19:10:55: OnCharacterStart

[Info   : Unity Log] 08/28/2023 19:10:57: Loading main scene

[Info   : Unity Log] 08/28/2023 19:10:58: Steam initialized, persona:Flux

[Info   : Unity Log] 08/28/2023 19:10:58: PlayFab custom ID set to "Steam_76561198005900763"

[Info   : Unity Log] 08/28/2023 19:10:58: Using default prefs

[Info   :Jotunn.Managers.CommandManager] Adding 1 commands to the Console
[Info   : Unity Log] 08/28/2023 19:10:58: Loading player profile local

[Info   : Unity Log] 08/28/2023 19:10:58: isModded: True

[Info   : Unity Log] 08/28/2023 19:10:58: Zonesystem Awake 1737

[Info   : Unity Log] 08/28/2023 19:10:58: DungeonDB Awake 1737

[Info   : Unity Log] 08/28/2023 19:10:58: Steam initialized, persona:Flux

[Info   : Unity Log] 08/28/2023 19:10:58: Worldgenerator version setup:2

[Info   : Unity Log] Registered 'FixItFelix.AutoMapPins ConfigSync' RPC - waiting for incoming connections
[Info   :Jotunn.Managers.PrefabManager] Adding 3 custom prefabs to the ZNetScene
[Info   : Unity Log] 08/28/2023 19:11:00: Audioman already exist, destroying self

[Info   : Unity Log] 08/28/2023 19:11:00: Checking for installed DLCs

[Info   : Unity Log] 08/28/2023 19:11:00: DLC:beta installed:False

[Info   :Jotunn.Managers.NetworkManager] Registering 2 custom RPCs
[Info   : Unity Log] 08/28/2023 19:11:03: Zonesystem Start 1737

[Info   : Unity Log] 08/28/2023 19:11:04: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from locations_cp1

[Info   : Unity Log] 08/28/2023 19:11:04: Added 1 locations, 0 vegetations, 2 environments, 0 biome env-setups, 0 clutter  from locations_mountaincaves

[Info   : Unity Log] 08/28/2023 19:11:04: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from locations_mistlands

[Info   : Unity Log] 08/28/2023 19:11:04: Added 4 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from locations_hildir

[Info   : Unity Log] 08/28/2023 19:11:04: DungeonDB Start 1737

[Info   : Unity Log] 08/28/2023 19:11:04: ZRpc timeout set to 30s

[Info   : Unity Log] 08/28/2023 19:11:04: Load world: local2 (local2)

[Info   : Unity Log] 08/28/2023 19:11:04: Loading 34722 zdos, my sessionID: 3061895616, data version: 32

[Info   : Unity Log] 08/28/2023 19:11:04: Creating ZDOs

[Info   : Unity Log] 08/28/2023 19:11:04: Loading in ZDOs

[Info   : Unity Log] 08/28/2023 19:11:04: Adding to Dictionary

[Info   : Unity Log] 08/28/2023 19:11:04: Adding to Sectors

[Info   : Unity Log] 08/28/2023 19:11:04: Connecting Portals, Spawners & ZSyncTransforms

[Info   : Unity Log] ConnectPortals => Connected 1 portals.
[Info   : Unity Log] 08/28/2023 19:11:04: Loaded 10174 locations

[Info   : Unity Log] 08/28/2023 19:11:04: Unloading unused assets

[Info   : Unity Log] 08/28/2023 19:11:05: Session auth respons callback

[Info   : Unity Log] 08/28/2023 19:11:12: Unpacking compressed mapdata 8769

[Info   :FixItFelix.AutoMapPins] Loaded map with 17 existing pins
[Info   : Unity Log] 08/28/2023 19:11:12: Starting respawn

[Info   : Unity Log] 08/28/2023 19:11:13: tip:$loadscreen_tip21

[Info   : Unity Log] 08/28/2023 19:11:20: Spawned after 8.019994

[Warning: Unity Log] 08/28/2023 19:11:20: Missing stat for guardian power:

[Info   : Unity Log] 08/28/2023 19:11:20: Skipping unloading unused assets

[Info   : Unity Log] 08/28/2023 19:11:20: Minimap: Adding unique location (-122.7, 33.7, 1.7)

[Info   : Unity Log] 08/28/2023 19:11:22: Starting music meadows

[Info   : Unity Log] 08/28/2023 19:11:22: Resumed music meadows at 0

[Info   : Unity Log] 08/28/2023 19:13:28: Starting music evening

[Info   : Unity Log] 08/28/2023 19:13:29: Stopped music meadows at 5605286

```

**Comment by ahmedadel2** [comment] 2023-08-31 07:39
Hello FelixReuthlinger,

I just ran the game with the mod only and Bepinx and Console is not working.
This is the log output

[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (7/19/2023 7:26:46 PM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2105 from Thunderstore
[Info   :   BepInEx] Running under Unity v2020.3.45.6687953
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [AutoMapPins 1.1.5]
[Info   :FixItFelix.AutoMapPins] found category and pin config file 'C:\Users\ahmad\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Test\BepInEx\config\FixItFelix.AutoMapPins.categories.vanilla.yaml'
[Info   :FixItFelix.AutoMapPins] loaded 16 categories and a total of 188 pins across all categories from configuration
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 08/31/2023 10:36:17: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 08/31/2023 10:36:17: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Info   : Unity Log] 08/31/2023 10:36:17: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 08/31/2023 10:36:25: Using environment steamid 892970

[Info   : Unity Log] 08/31/2023 10:36:25: Using steam APPID:892970

[Info   : Unity Log] 08/31/2023 10:36:25: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 08/31/2023 10:36:25: Steam initialized, persona:Arrow

[Info   : Unity Log] 08/31/2023 10:36:25: PlayFab custom ID set to "Steam_76561199145346957"

[Info   : Unity Log] 08/31/2023 10:36:25: Using default prefs

[Info   : Unity Log] 08/31/2023 10:36:25: Valheim version: 0.217.14 (network version 12)

[Info   : Unity Log] 08/31/2023 10:36:25: Worldgenerator version setup:2

[Error  : Unity Log] MissingMethodException: void Terminal/ConsoleCommand..ctor(string,string,Terminal/ConsoleEvent,bool,bool,bool,bool,bool,Terminal/ConsoleOptionsFetcher)
Stack trace:
(wrapper dynamic-method) Console.DMD<Console::Awake>(Console)
UnityEngine.Object:Instantiate(GameObject)
FejdStartup:Awake()

[Info   : Unity Log] 08/31/2023 10:36:25: Render threading mode:MultiThreaded

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 08/31/2023 10:36:25: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Warning: Unity Log] 08/31/2023 10:36:25: Missing audio clip in music respawn

[Info   : Unity Log] 08/31/2023 10:36:25: Checking for installed DLCs

[Info   : Unity Log] 08/31/2023 10:36:25: DLC:beta installed:False

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab Advanced_Merged_Gemstone_Orange_Black

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab rk_chef

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab BH_EmptyContainer

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab JC_Gem_Bag

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab Perfect_Blue_Socket

[Info   : Unity Log] 08/31/2023 10:36:25: Failed to find item prefab BlueprintRune

[Info   : Unity Log] 08/31/2023 10:36:25: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 08/31/2023 10:36:25: Ticket is System.Byte[] of length 369

[Info   : Unity Log] 08/31/2023 10:36:25: Session auth respons callback

[Info   : Unity Log] 08/31/2023 10:36:25: Starting music menu

[Info   : Unity Log] 08/31/2023 10:36:27: PlayFab logged in as "Steam_76561199145346957"

[Info   : Unity Log] 08/31/2023 10:36:27: PlayFab local entity ID is BC622468AA3E01E8

[Info   : Unity Log] 08/31/2023 10:36:52: Stopping build thread

[Info   : Unity Log] 08/31/2023 10:36:53: Steam manager on destroy

**Comment by FelixReuthlinger** [comment] 2023-08-31 18:29
ok, but how should I reproduce this?

**Comment by ahmedadel2** [comment] 2023-08-31 23:18
I am using the R2modman mod manager (version 3.1.43).

Steps are:

1- Create a new profile
2- Add AutoMapPins from Online
3- Start Modded.

**Comment by FelixReuthlinger** [comment] 2023-09-01 19:18
Ok, did double check it to download and run with mod manager and with that I also did see the error. When just compiling I didn't. 
But well, fixed now ;)

**Closed as completed by FelixReuthlinger** 2023-09-01 19:18 UTC

**Comment by BinaryConstruct** [comment] 2023-09-01 21:01
[edit] the issue below is fixed with 1.1.7


This update seems to have a conflict with the ComfortTweaks by smoothbrain that causes a `Crash to Desktop`. I'm not sure if the issue is here or there, so I was dropping a note in both places.

Reproduction Steps:

Create new profile in thunderstore.
Install
- BepInEx by denikson 5.4.2105
- AutoMapPins by FixItFelix 1.1.6
- ComfortTweaks by Smoothbrain 3.2.1

![image](https://github.com/FelixReuthlinger/AutoMapPins/assets/456755/5f243b31-170e-47bf-8542-998109792621)


NOTE: rolling back to 1.1.5 resolves this crash.
```log
[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (8/28/2023 6:30:24 PM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2105 from Thunderstore
[Info   :   BepInEx] Running under Unity v2020.3.45.6687953
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [AutoMapPins 1.1.6]
[Warning: Unity Log] The script 'AutoMapPins.AutoMapPinsPlugin' could not be instantiated!
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Info   :   BepInEx] Loading [Comfort Tweaks 3.2.0]
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:16: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 09/01/2023 15:56:17: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Warning: Unity Log] 09/01/2023 15:56:17: Fetching PlatformPrefs 'GuiScale' before loading defaults
[Info   : Unity Log] 09/01/2023 15:56:17: Starting to load scene:start
[Info   : Unity Log] 09/01/2023 15:56:17: Using environment steamid 892970
[Info   : Unity Log] 09/01/2023 15:56:17: Using steam APPID:892970
[Info   : Unity Log] 09/01/2023 15:56:17: Authentication:k_ESteamNetworkingAvailability_Attempting
[Error  :   BepInEx] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF+iHUtTkyFXuOkHcrwdpjyWzQmaLde.nOjOHazOtrXOLfMaIjGsDmtnvsCAA (BepInEx.BaseUnityPlugin ) [0x00000] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF+YkQpGSDOGLPMIpFDRiOSaJHmlwnNA.iIDvKWPsvASYsoDvJPzBJEsUmrVn () [0x001f9] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <695d1cc93cca45069c528c15c9fdd749>:0 
   --- End of inner exception stack trace ---
  at BepInEx.ThreadingHelper.System.ComponentModel.ISynchronizeInvoke.EndInvoke (System.IAsyncResult result) [0x00013] in <fe49c90fe8e24102b42489c11910c71c>:0 
  at BepInEx.ThreadingHelper.System.ComponentModel.ISynchronizeInvoke.Invoke (System.Delegate method, System.Object[] args) [0x00009] in <fe49c90fe8e24102b42489c11910c71c>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF.‍⁭‬⁮‎​‫⁯‮⁭⁯‫⁮⁫‌⁮⁮⁫⁭⁬‏‌⁭‬⁭‎⁫‪⁮​⁫‬‫‌‭⁮‪‫⁬⁮‮ (System.ComponentModel.ISynchronizeInvoke , System.Delegate , System.Object[] ) [0x00000] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF.ivyWEQeruVZvoYovAsAWAHtlumXe () [0x00032] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF.vkLaohJDzwPyARIZmOWIiYPcMbEFA () [0x00015] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF.JJSExgAIQwnnOchZAvlZiXXxUKXcb () [0x00116] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at BepInEx.ThreadingHelper.Update () [0x0005a] in <fe49c90fe8e24102b42489c11910c71c>:0 
[Error  :   BepInEx] INNER: System.NullReferenceException: Object reference not set to an instance of an object
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF+iHUtTkyFXuOkHcrwdpjyWzQmaLde.nOjOHazOtrXOLfMaIjGsDmtnvsCAA (BepInEx.BaseUnityPlugin ) [0x00000] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at hOXGcwTtgmCyGhWPCKrOWufFLnsF+YkQpGSDOGLPMIpFDRiOSaJHmlwnNA.iIDvKWPsvASYsoDvJPzBJEsUmrVn () [0x001f9] in <123bad227e1d4d3e991fa9f3e8485d88>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <695d1cc93cca45069c528c15c9fdd749>:0 
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 09/01/2023 15:56:23: Steam initialized, persona:[REDACTED]
[Info   : Unity Log] 09/01/2023 15:56:23: PlayFab custom ID set to "Steam_redacted"
[Info   : Unity Log] 09/01/2023 15:56:23: Using default prefs
[Info   : Unity Log] 09/01/2023 15:56:23: Valheim version: 0.217.14 (network version 12)
[Info   : Unity Log] 09/01/2023 15:56:23: Worldgenerator version setup:2
[Info   : Unity Log] 09/01/2023 15:56:23: Render threading mode:MultiThreaded
[Warning: Unity Log] 09/01/2023 15:56:23: Missing audio clip in music respawn
[Info   : Unity Log] 09/01/2023 15:56:23: Checking for installed DLCs
[Info   : Unity Log] 09/01/2023 15:56:23: DLC:beta installed:False
[Warning: Unity Log] Error loading player data: C:/Users/redacted/AppData/LocalLow/IronGate/Valheim/characters_local/redacted.fch, error: Exception has been thrown by the target of an invocation.
[Info   : Unity Log] 09/01/2023 15:56:23: Sending PlayFab login request (attempt 1)
[Info   : Unity Log] 09/01/2023 15:56:23: Session auth respons callback
[Info   : Unity Log] 09/01/2023 15:56:23: Starting music menu
[Info   : Unity Log] 09/01/2023 15:56:24: Stopping build thread
[Info   : Unity Log] 09/01/2023 15:56:24: Steam manager on destroy
```

**Comment by FelixReuthlinger** [comment] 2023-09-02 07:15
Thx for reporting, I doubt it was AutoMapPins, since
```
[Info   :   BepInEx] Loading [AutoMapPins 1.1.6]
[Warning: Unity Log] The script 'AutoMapPins.AutoMapPinsPlugin' could not be instantiated!
```
points out it had problems loading, probably need to recompile and publish new version again

**Comment by BinaryConstruct** [comment] 2023-09-03 22:15
Maybe not, the crash seems to occur whenever the character is loaded. If all character saves are removed, the crash doesn't occur until you attempt to create a character.

Anyway, thanks for the response. The update (1.1.7) does seem to resolve the issue.
